### ISSUE TITLE
启动时mysql报错

### ISSUE THREAD

**Issue by w0ngge** [Aur0ra-m/APIKiller#3]
报错如下，系统版本为intel macos 11.7.2 ，数据库版本为MYSQL_VERSION=5.7.41-1.el7
<img width="1856" alt="image" src="https://user-images.githubusercontent.com/105301722/224249833-25f2f62b-fe93-4a6a-a17e-c475f1ec8f4b.png">

**Comment by Aur0ra-m** [comment]
可能是ip配置存在问题，docker做了端口映射，你将ip换为本机端口即可
