### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mo718** [Aur0ra-m/APIKiller#5]
在Ubuntu上运行时发生如下错误：
![image](https://user-images.githubusercontent.com/64512529/233823252-80900be2-2d79-4b9c-94e7-aea5239cfe28.png)
数据库是通过docker部署的
数据库日志信息显示
![image](https://user-images.githubusercontent.com/64512529/233823288-d4aea0f0-4519-401b-a1ce-955da0aa6d6e.png)
请问是哪里出错了？

**Comment by Aur0ra-m** [comment]
看样子应该不是数据库的原因，好像是这个异步检测引擎依赖的在线平台有问题

**Comment by Aur0ra-m** [comment]
项目针对这种情况做了如下更细处理：先进行反连平台的存活检测，避免因反连平台的问题，导致当前项目down掉。但如果反连平台是down的状态，针对ssrf这种，暂时就无法检测处理了。这也是当前依赖第三方反连平台的一种弊端。后续会推进自研反连平台的研发工作。

**Comment by Aur0ra-m** [comment]
项目针对这种情况做了如下更新处理：先进行反连平台的存活检测，避免因反连平台的问题，导致当前项目down掉。但如果反连平台是down的状态，针对SSRF这种，暂时就无法进行检测处理了。这也是当前依赖第三方反连平台的一种弊端。后续会推进自研反连平台的研发工作。

**Comment by mo718** [comment]
好的，谢谢
