### ISSUE TITLE
Error 1054 (42S22): Unknown column 'item' in 'field list'

### ISSUE THREAD

**Issue by mo718** [Aur0ra-m/APIKiller#6]
你好，能解释一下http_items这个表的含义吗？我在检测vapi靶场的越权漏洞时，发生了如下错误：
![image](https://user-images.githubusercontent.com/64512529/234013616-8565632a-8cc1-4307-a6e7-f0f540b3a018.png)

**Comment by Aur0ra-m** [comment]
你将数据库中的http_items表中的paramItem改成item就可以了
